### ISSUE TITLE
What is every character meaning of SLUBStick ?

### ISSUE THREAD

**Issue by ZhiboWong** [IAIK/SLUBStick#2]
Please tell me the full name.

**Comment by lukasmaar** [comment]
SLUBStick combines the word "slapstick" (the style of humor) with the word "SLUB" (the most used implementation of the Linux's slab allocator). We have also created a logo to highlight this combination:

![SLUBStick](https://github.com/user-attachments/assets/43afbd6f-20de-4fe5-8611-aed2d0184add)
